### ISSUE TITLE
Are we happy with the api?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gflanguages#6]
We only have four functions which live in the module `gflanguages.lang_support`. This module is also the only module that we have.  Couldn't these functions just live in the `__init__` file?

Moving them to the `__init__` means we'll get more concise import statement e.g

`from gflanguages import LoadScripts`. We currently have to do `from gflanguages.lang_support import LoadScripts`.

**Comment by felipesanches** [comment]
I agree. I will do this today and then I'll cut a new release, then update this PR to use the module that way.

**Comment by felipesanches** [comment]
done. Now I'll update the fontbakery usage as well as the gftools PR
